import 'quill/dist/quill.snow.css';

export const metadata = {
    title: 'Blog Web Site | Create New Blog',
    description: 'Generated by next app',
    author: "Md. Mehedi Hasan Nabil"
}

export default function Layout({ children }) {
    return (
        <>
            <nav>
                <div className='container py-5 shadow-md mb-3'>
                
                <h2>Write Your Blog</h2>
                </div>
            </nav>
            {children}
        </>

    )
}
