import Link from "next/link";
import "../default.css";
import Image from "next/image";
import logo from "../../../public/logo.png"

export const metadata = {
  title: "Blog Web Site | Create New Blog",
  description: "Generated by next app",
  author: "Md. Mehedi Hasan Nabil",
};

export default function Layout({ children }) {
  return (
    <>
      <nav>
        <div className="container py-3 mb-3 flex justify-between items-center">
          <Link href="/" className="font-bold text-xl">
            <Image
              className="w-32"
              src={logo}
              width={500}
              height={500}
              alt="logo"
            />
          </Link>
          <div className="flex items-center gap-4">
            <button className="bg-red-600 px-4 py-1 rounded-full text-white">
              Publish
            </button>
            <div>Profile</div>
          </div>
        </div>
      </nav>
      {children}
    </>
  );
}
